# These are supported funding model platforms

github: [cxthub]
# patreon: # your-patreon
# open_collective: # your-opencollective
# ko_fi: # your-kofi
# tidelift: # npm/your-package
# community_bridge: # your-project
# liberapay: # your-liberapay
# issuehunt: # your-issuehunt
# otechie: # your-otechie
# lfx_crowdfunding: # your-crowdfunding
# custom: # your-custom-url
